apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-app-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: ecommerce-app-secret
    creationPolicy: Owner
  data:
  - secretKey: MONGO_URI
    remoteRef:
      key: ecommerce-app/dev/db
      property: MONGO_URI
  - secretKey: JWT_SECRET
    remoteRef:
      key: ecommerce-app/dev/db
      property: JWT_SECRET
