replicaCount: 2

image:
  repository: 761288221961.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-client
  tag: latest

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

serviceAccount:
  create: false

ingress:
  enabled: false

httpRoute:
  enabled: false
