apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gulmaan-app-secrets
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: gulmaan-app-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: gulmaan-app/dev/db
      property: DB_PASSWORD
